captainVersion: 4
services:
    $$cap_appname:
        image: prom/prometheus:$$cap_version
        restart: always
        volumes:
            - $$cap_appname-config:/etc/prometheus
            - $$cap_appname-data:/prometheus
        caproverExtra:
            containerHttpPort: '9090'
        user: 0:0
caproverOneClickApp:
    variables:
        - label: Prometheus Version Tag
          defaultValue: 'v2.28.0'
          description: Find on Docker Hub.  Default is latest as of 2021-06-23.
          id: $$cap_version
    instructions:
        end: Prometheus is now starting.
        start: 'Read more about Prometheus: https://prometheus.io/'
    displayName: Prometheus
    isOfficial: true
    description: Prometheus is a systems and service monitoring system.
    documentation: https://hub.docker.com/r/prom/prometheus/
