captainVersion: 4
services:
    $$cap_appname:
        image: ericmathison/sendy:$$cap_sendy_version
        restart: always
        volumes:
            - $$cap_appname-data:/var/www/html
        environment:
            SENDY_FQDN: $$cap_sendy_fqdn
            MYSQL_HOST: srv-captain--$$cap_sendy_db_host
            MYSQL_USER: $$cap_sendy_db_user
            MYSQL_PASSWORD: $$cap_sendy_db_password
            MYSQL_DATABASE: sendy
caproverOneClickApp:
    variables:
        - id: $$cap_sendy_db_host
          label: MySQL Host
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_db_user
          label: Sendy Database User Name
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_db_password
          label: Sendy Database Password
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_version
          label: Sendy Version Tag
          description: 'Check out their Docker page for the valid tags: https://hub.docker.com/r/ericmathison/sendy?tab=tags'
          defaultValue: '5.2'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_sendy_fqdn
          label: Sendy FQDN
          validRegex: /^(\w|[^\s"])+$/
    instructions:
        start: >-
            Sendy No Database Deployment
        end: >
            Deployment has finished.
    displayName: 'Sendy No Database'
    isOfficial: true
    description: Sendy No Database Deployment
    documentation: none
