captainVersion: 4
services:
    $$cap_appname-db:
        image: ericmathison/mariadb:$$cap_mariadb_version
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_mysql_root_password
            MYSQL_DATABASE: sendy
            MYSQL_USER: $$cap_sendy_db_user
            MYSQL_PASSWORD: $$cap_sendy_db_password
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        image: ericmathison/sendy:$$cap_sendy_version
        depends_on:
            - $$cap_appname-db
        restart: always
        environment:
            SENDY_FQDN: $$cap_sendy_fqdn
            MYSQL_HOST: srv-captain--$$cap_appname-db
            MYSQL_USER: $$cap_sendy_db_user
            MYSQL_PASSWORD: $$cap_sendy_db_password
            MYSQL_DATABASE: sendy
caproverOneClickApp:
    variables:
        - id: $$cap_mariadb_version
          label: MariaDB Version Tag
          description: 'Check out their Docker page for the valid tags: https://hub.docker.com/r/ericmathison/mariadb?tab=tags'
          defaultValue: '10'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mysql_root_password
          label: MySQL Root Password
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_db_user
          label: Sendy Database User Name
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_db_password
          label: Sendy Database Password
          validRegex: /^(\w|[^\s"])+$/
        - id: $$cap_sendy_version
          label: Sendy Version Tag
          description: 'Check out their Docker page for the valid tags: https://hub.docker.com/r/ericmathison/sendy?tab=tags'
          defaultValue: '5.2'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_sendy_fqdn
          label: Sendy FQDN
          validRegex: /^(\w|[^\s"])+$/
    instructions:
        start: >-
            Sendy + MariaDB Deployment
        end: >
            Deployment has finished.
    displayName: ''
    isOfficial: true
    description: Sendy + MariaDB Deployment
    documentation: none
